# Generated by Django 3.2.7 on 2021-10-05 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='PUBLISHED', max_length=10)),
                ('category', models.CharField(choices=[('TC', 'Tecnologia'), ('SP', 'Sport'), ('SL', 'Salute'), ('TL', 'Tempo Libero')], default='TL', max_length=2)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('img', models.ImageField(blank=True, upload_to='uploads')),
                ('content', models.TextField(max_length=5000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated', '-published'),
            },
        ),
    ]
