# Generated by Django 3.2.7 on 2021-10-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('TC', 'Technology'), ('SP', 'Sport'), ('WL', 'Wellness'), ('AN', 'Anime'), ('FT', 'Free time')], default='FT', max_length=2),
        ),
    ]
