# Generated by Django 3.2.7 on 2021-11-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('TC', 'Technology'), ('BC', 'Blockchain'), ('SP', 'Sport'), ('GC', 'General culture'), ('AN', 'Anime'), ('FT', 'Free time')], default='FT', max_length=2),
        ),
    ]
