# Generated by Django 3.2.7 on 2021-11-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='txId',
            field=models.CharField(default=None, max_length=66, null=True),
        ),
    ]
