# Generated by Django 3.2.7 on 2021-11-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20211104_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='address',
            field=models.CharField(default=None, max_length=66, null=True),
        ),
    ]
