# Generated by Django 3.2.7 on 2021-10-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_ip_address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='UserIP',
        ),
    ]
