# Generated by Django 3.2.7 on 2021-10-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211030_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_ip_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='ip_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
